apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "name" . }}
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: [""]
    resources: ["pods", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["get"]
