apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "name" .) }}
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/managed-by: Helm
